sudo: required
services:
  - docker

before_install:
  - docker build -t icannomnoms/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true icannomnoms/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-2-444498778794"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: "$aws"
  secret_access_key: "$aws_secret"